volumes:
  dados:

networks:
  web:
    driver: bridge
    
services:  

  app:
    image: php:7.3.21-apache
    container_name: app
    working_dir: /var/www/html/
    command: bash ./app.sh
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    networks:
      - web
    restart: always

  db:
    image: mysql:8.4.2
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: processo_de_aquisicao
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
    ports:
      - 3306:3306
    volumes:
      # Volume dos dados
      - dados:/var/lib/mysql
      # Scripts
      - ./db:/docker-entrypoint-initdb.d
    networks: 
      - web

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - web
    depends_on:
      - db
    restart: always
