use processo_de_aquisicao;

INSERT INTO 
`artefato`(`id`,`nome`,`status`) 
VALUES 
('1','Capa',true),
('2','Índice',true),
('3','Termo De Autuação',true),
('4','Nomeação Do Cmt Da Unidade',true),
('5','Nomeação Da Equipe Da Contratação',true),
('6','Nomeação De Pregoeiro Equipe De Apoio',true),
('7','Certificado Do Pregoeiro',true),
('8','Documento De Formalização Da Demanda - DFD',true),
('9','Relação De Itens De Aquisição/ Serviço',true),
('10','Autorização P/ Abertura De Processo',true),
('11','ETP – Estudo Técnico Preliminar',true),
('12','MGR – Mapa De Gerenciamento De Riscos',true),
('13','Minuta TR Da Sç Demandante',true),
('14','Aprovação ETP E TR',true),
('15','Relatório Pesquisa De Preços – RPP',true),
('16','Pesquisas De Preços – PP',true),
('17','Mapa Comparativo De Preços – MCP',true),
('18','Quadro IRP',true),
('19','Aviso de Abertura de IRP À 5ª CGCFEx',true),
('20','Minuta Do Edital',true),
('21','Minuta Do Termo De Referência – TR Da SALC',true),
('22','Minuta Da ARP',true),
('23','Minuta De Contrato',true),
('24','Declaração Inexistência De Atas',true),
('25','Declaração De Natureza Do Objeto',true),
('26','Declaração De Atividade De Custeio',true),
('27','Declaração De Adequação Orçamentária',true),
('28','Justificativa De PE SRP',true),
('29','Justificativa Para Alteraçõeses Das Minutas',true),
('30','Justificativa de não exclusividade para ME/EPP',true),
('31','Lista De Verificação - Anexo I Da SEGE',true),
('32','Lista De Verificação - Anexo II Da SEGE',true),
('33','Ofício Para CJU Analisar Processo',true),
('34','Ofício De Remessa Da CJU',true),
('35','Parecer Da CJU',true),
('36','Pedidos de impugnação',true),
('37','Decisão sobre pedidos de impugnação',true),
('38','Pedidos de esclarecimentos',true),
('39','Esclarecimentos publicado',true),
('40','Edital Revisado',true),
('41','TR Revisado',true),
('42','Minuta ARP Revisado',true),
('43','Minuta Contrato Revisado',true),
('44','Aviso(s) de publicação(ões) no DOU',true),
('45','ARP Assinada',true),
('46','Contrato assinado',true),
('47','Termo De Encerramento',true);
