use processo_de_aquisicao;

INSERT INTO `artefato`(`id`,`ordem`,`nome`,`status`) VALUES 
(1,1,'Capa',true),
(2,2,'Índice',true),
(3,3,'Termo De Autuação',true),
(4,4,'Nomeação Do Cmt Da Unidade',true),
(5,5,'Nomeação Da Equipe Da Contratação',true),
(6,6,'Nomeação De Pregoeiro Equipe De Apoio',true),
(7,7,'Certificado Do Pregoeiro',true),
(8,8,'Documento De Formalização Da Demanda - DFD',true),
(9,9,'Relação De Itens De Aquisição/ Serviço',true),
(10,10,'Autorização P/ Abertura De Processo',true),
(11,11,'ETP – Estudo Técnico Preliminar',true),
(12,12,'Projeto Básico',true),
(13,13,'Projeto Executivo',true),
(14,14,'MGR – Mapa De Gerenciamento De Riscos',true),
(15,15,'Minuta TR Da Sç Demandante',true),
(16,16,'Aprovação ETP E TR',true),
(17,17,'Relatório Pesquisa De Preços – RPP',true),
(18,18,'Pesquisas De Preços – PP',true),
(19,19,'Mapa Comparativo De Preços – MCP',true),
(20,20,'Quadro IRP',true),
(21,21,'Aviso de Abertura de IRP À 5ª CGCFEx',true),
(22,22,'Minuta Do Edital',true),
(23,23,'Minuta Do Termo De Referência – TR Da SALC',true),
(24,24,'Minuta Da ARP',true),
(25,25,'Minuta De Contrato',true),
(26,26,'Declaração Inexistência De Atas',true),
(27,27,'Declaração De Natureza Do Objeto',true),
(28,28,'Declaração De Atividade De Custeio',true),
(29,29,'Declaração De Adequação Orçamentária',true),
(30,30,'Justificativa De PE SRP',true),
(31,31,'Justificativa Para Alterações Das Minutas',true),
(32,32,'Justificativa de não exclusividade para ME/EPP',true),
(33,33,'Lista De Verificação - Anexo I Da SEGE',true),
(34,34,'Lista De Verificação - Anexo II Da SEGE',true),
(35,35,'Ofício Para CJU Analisar Processo',true),
(36,36,'Ofício De Remessa Da CJU',true),
(37,37,'Parecer Da CJU',true),
(38,38,'Nota Explicativa',true),
(39,39,'Pedidos de impugnação',true),
(40,40,'Decisão sobre pedidos de impugnação',true),
(41,41,'Pedidos de esclarecimentos',true),
(42,42,'Esclarecimentos publicado',true),
(43,43,'Edital Revisado',true),
(44,44,'TR Revisado',true),
(45,45,'Minuta ARP Revisado',true),
(46,46,'Minuta Contrato Revisado',true),
(47,47,'Aviso(s) de publicação(ões) no DOU',true),
(48,48,'ARP Assinada',true),
(49,49,'Contrato assinado',true),
(50,50,'Cotação Eletrônica',true),
(51,51,'Troca de E-mail ou Ofício com Fornecedor',true),
(52,52,'Proposta do Fornecedor',true),
(53,53,'DIEx de Requisitória',true),
(54,54,'Termo de Dispensa de Licitação',true),
(55,55,'Regularidade Fiscal - CNJ',true),
(56,56,'Regularidade Fiscal – CEIS',true),
(57,57,'Regularidade Fiscal – TCU',true),
(58,58,'Regularidade Fiscal – CADIN',true),
(59,59,'Regularidade Fiscal – SICAF (FGTS, RF, TRABALHISTA)',true),
(60,60,'Regularidade FGTS',true),
(61,61,'Regularidade RF',true),
(62,62,'Regularidade TRABALHISTA',true),
(63,63,'Nota de Empenho',true),
(64,64,'Termo De Encerramento',true);